//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinemafilmarsiv
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFILMLER
    {
        public short ID { get; set; }
        public string AD { get; set; }
        public string KATEGORI { get; set; }
        public string LINK { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
