--select count(*) As 'Toplam Kiþi' from TBLOGRENCILER --AS baþlýðý belirler
--select count(*) As 'Toplam kisi' from TBLOGRENCILER where OGRSEHIR='TOKAT'
--select sum(SINAV1) AS 'Toplam kiþi', SUM(SINAV2) AS 'Toplam kiþi', SUM(SINAV3) AS 'Toplam kiþi' FROM TBLNOTLAR
--SELECT AVG(SINAV1), AVG(SINAV2), AVG(SINAV3) FROM TBLNOTLAR
--SELECT min(SINAV1), min(SINAV2), min(SINAV3) FROM TBLNOTLAR
--SELECT max(SINAV1), max(SINAV2), max(SINAV3) FROM TBLNOTLAR

--update TBLNOTLAR set ORTALAMA=(SINAV1+SINAV2+SINAV3)/3
--update TBLNOTLAR set DURUM=1 where ORTALAMA>=50
--update TBLNOTLAR set DURUM=0 where ORTALAMA<50
--GROUP BY, AS
--SELECT DURUM, COUNT(*) AS 'TOPLAM'  FROM TBLNOTLAR GROUP BY DURUM
--HAVING
--SELECT OGRCINSIYET, COUNT(*) AS'TOPLAM' FROM TBLOGRENCILER GROUP BY OGRCINSIYET HAVING OGRCINSIYET='ERKEK'
--SELECT OGRSEHIR, COUNT(*) FROM TBLOGRENCILER GROUP BY OGRSEHIR HAVING COUNT(*)=2
--SELECT DURUM, COUNT(*) AS 'GEÇENLER' FROM TBLNOTLAR GROUP BY DURUM HAVING DURUM=1
--LIKE
--SELECT * FROM TBLOGRENCILER WHERE OGRAD like 'a%'--baþýnda a olanlarý getir
--SELECT * FROM TBLOGRENCILER WHERE OGRKULUP like '%a%'--ortasýnda a geçenler
--SELECT * FROM TBLOGRENCILER WHERE OGRSOYAD not like '%b%'-- ortasýnda b geçmeyenler
--DISTINCT
--SELECT OGRKULUP AS 'KULÜPLER' FROM TBLOGRENCILER
--SELECT DISTINCT OGRKULUP AS 'KULÜPLER' FROM TBLOGRENCILER--DISTINCT BÝLGÝLERÝ TEKRARSIZ VERÝR
--SELECT COUNT(OGRSEHIR) AS 'SEHÝRLER' FROM TBLOGRENCILER
--SELECT COUNT(DISTINCT OGRSEHIR) AS 'SEHÝRLER' FROM TBLOGRENCILER
--SELECT  OGRSEHIR FROM TBLOGRENCILER order by OGRAD ASC--sehýrlerý öðrenci adýnýn sentaksýna 
--sýralar

--ORDER BY ASCENDING(ASC a'dan z'ye), DESCENDING(DESC z'den a'ya)
--SELECT  OGRSEHIR FROM TBLOGRENCILER order by OGRAD ASC--sehýrlerý öðrenci adýnýn sentaksýna 
--sýralar
--SELECT OGRKULUP FROM TBLOGRENCILER order by OGRKULUP DESC--KULUPLERI  z'den a'ya sýralar
--SELECT  OGRSEHIR FROM TBLOGRENCILER order by OGRSEHIR ASC--kulüpleri a'dan z'ye sýralar




