//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlDoviz_Uygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOVIZKASA
    {
        public int ISLEMID { get; set; }
        public Nullable<decimal> DOLAR { get; set; }
        public Nullable<decimal> EURO { get; set; }
        public Nullable<decimal> TL { get; set; }
    }
}
